cbtv02/urls.py
"""
Definition of urls for cbtv02.
"""

from datetime import datetime
from django.conf.urls import url
import django.contrib.auth.views
from django.conf.urls.static import static
import app.forms
import app.views
from cbtv02 import settings
# Uncomment the next lines to enable the admin:
from django.conf.urls import include
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    # Examples:
    url(r'^$', app.views.home, name='home'),
    url(r'^contact$', app.views.contact, name='contact'),
    url(r'^about', app.views.about, name='about'),
    url(r'^register', app.views.register, name='register'),
    url(r'^boardpage', app.views.boardpage, name='boardpage'),
    url(r'^result', app.views.result, name='result'),
    url(r'^reset', app.views.reset, name='reset'),
    #url(r'^questionpage/(?P<module>\w+)', app.views.questionpage, name='questionpage'),
    url(r'^questionpage', app.views.questionpage, name='questionpage'),
    url(r'^postanswer', app.views.postanswer, name='postanswer'),
    url(r'^get_answer', app.views.get_answer, name='get_answer'),
    url(r'^legibility', app.views.legible, name='legible'),
    url(r'^booklet/', app.views.booklet, name='booklet'),
    #url(r'^login/$',
    #    django.contrib.auth.views.login,
    #    {
    #        'template_name': 'app/login.html',
    #        'authentication_form': app.forms.BootstrapAuthenticationForm,
    #        'extra_context':
    #        {
    #            'title': 'Log in',
    #            'year': datetime.now().year,
    #        }
    #    },
    #    name='login'),
    url(r'^login/$',app.views.mylogin,name='login'),
    url(r'^logout$',
        django.contrib.auth.views.logout,
        {
            'next_page': '/',
        },
        name='logout'),

    # Uncomment the admin/doc line below to enable admin documentation:
     url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
     url(r'^admin/', include(admin.site.urls),name='adminlink'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

app/models.py
"""
Definition of models.
"""

from django.db import models
from django.contrib.auth.models import  User
from datetime import datetime
from django.core.exceptions import ValidationError






class Cbt_role(models.Model):
    role_name=models.CharField(max_length=200)
    class Meta:
        verbose_name='CBT ROLE'
        verbose_name_plural='CBT ROLES'

    def __str__(self):
        return str(self.role_name)

class Cbt_user(models.Model):
    firstname=models.CharField(max_length=200,blank=True)
    surname=models.CharField(max_length=200,blank=True)
    middlename=models.CharField(max_length=200,blank=True)
    username=models.CharField(max_length=200,blank=True)
    

    def save(self,**kwargs):
        self.username=self.firstname+"_"+self.middlename
        return super().save(**kwargs)

    def __str__(self):
        return str(self.username)

class Cbt_modules(models.Model):

    MODULE_STATUS_CHOICES=(
        ('UNSCHEDULED','UNSCHEDULED'),
        ('SCHEDULED','SCHEDULED'),
        ('IN-PROGRESS','IN-PROGRESS'),
        ('ENDED','ENDED')
        )

    name=models.CharField(max_length=200)
    code=models.CharField(max_length=10)
    status=models.CharField(max_length=20,choices=MODULE_STATUS_CHOICES,default='UNSCHEDULED')
    class Meta:
        verbose_name='CBT MODULE'
        verbose_name_plural='CBT MODULES'
        
    def __str__(self):

        return "{}".format(self.code)

class Cbt_department(models.Model):
    name=models.CharField(max_length=200)
    moduless=models.ManyToManyField(Cbt_modules,blank=True)

    class Meta:
        verbose_name='CBT DEPARTMENT'
        verbose_name_plural='CBT DEPARTMENTS'
    def __str__(self):

        return "{}".format(self.name)



class Cbt_examiner(models.Model):
    user=models.OneToOneField(User)
    staffid=models.CharField(max_length=10)
    modules=models.ManyToManyField(Cbt_modules,blank=True)

    class Meta:
        verbose_name='CBT EXAMINER'
        verbose_name_plural='CBT EXAMINER'
    def __str__(self):
        return self.user.username


class Cbt_faculty(models.Model):
    name=models.CharField(max_length=200)
    department=models.ManyToManyField(Cbt_department,default="")

    class Meta:
        verbose_name='CBT FACULTY'
        verbose_name_plural='CBT FACULTIES'

    def __str__(self):

        return "{}".format(self.name).upper()

class Cbt_level(models.Model):
    name=models.CharField(max_length=10,default="100L")

    class Meta:
        verbose_name='CBT LEVEL'
        verbose_name_plural='CBT LEVELS'
    def save(self,**kwargs):
        self.name=self.name.upper()
        return super().save(**kwargs)

    def __str__(self):

        return self.name

class Cbt_semester(models.Model):
    SEMESTERS=(
        ("FIRST SEMESTER","FIRST SEMESTER"),
               
       ("SECOND SEMESTER","SECOND SEMESTER"),
       )
    name=models.CharField(max_length=20,choices=SEMESTERS,default="")

    class Meta:
        verbose_name='CBT SEMESTER'
        verbose_name_plural='CBT SEMESTERS'

    def __str__(self):
        return self.name
    


        
class Cbt_questions(models.Model):


    def photopath(self,filename):

        return 'question/'+self.module.code+'/'+str(datetime.today().year)+'/'+str(datetime.today().month)+'/'+filename

    QUESTION_TYPES=(
    ('SINGLE','SINGLE'),
    ('MULTIPLE','MULTIPLE')
    )

    question=models.TextField(default="")
    question_with_image=models.BooleanField(default=False)
    question_image=models.FileField(upload_to=photopath,blank=True)
    question_code=models.CharField(max_length=50,default="")
    level=models.ForeignKey(Cbt_level,default="")
    semester=models.ForeignKey(Cbt_semester,default="")
    module=models.ForeignKey(Cbt_modules,default="")
    scheduled=models.BooleanField(default=False)
    creator=models.ForeignKey(Cbt_examiner)
    questiontype=models.CharField(max_length=20,choices=QUESTION_TYPES,default='SINGLE',blank=True)
    answer=models.CharField(max_length=10,default="",blank=True)
    #answerd=models.BooleanField(default=False)
    optionA=models.CharField(max_length=200,default="",blank=True,verbose_name="Option A")
    optionA_with_image=models.BooleanField(default=False)
    optionA_image=models.FileField(upload_to='question/%Y/%m/%d',blank=True)
    optionB=models.CharField(max_length=200,default="",blank=True,verbose_name="Option B")
    optionB_with_image=models.BooleanField(default=False)
    optionB_image=models.FileField(upload_to='question/%Y/%m/%d',blank=True)
    optionC=models.CharField(max_length=200,default="",blank=True,verbose_name="Option C")
    optionC_with_image=models.BooleanField(default=False)
    optionC_image=models.FileField(upload_to='question/%Y/%m/%d',blank=True)
    optionD=models.CharField(max_length=200,default="",blank=True,verbose_name="Option D")
    optionD_with_image=models.BooleanField(default=False)
    optionD_image=models.FileField(upload_to='question/%Y/%m/%d',blank=True)
    optionE=models.CharField(max_length=200,default="",blank=True,verbose_name="Option E")
    optionE_with_image=models.BooleanField(default=False)
    optionE_image=models.FileField(upload_to='question/%Y/%m/%d',blank=True)
    optionF=models.CharField(max_length=200,default="",blank=True,verbose_name="Option F")
    optionF_with_image=models.BooleanField(default=False)
    optionF_image=models.FileField(upload_to='question/%Y/%m/%d',blank=True)
    optionG=models.CharField(max_length=200,default="",blank=True,verbose_name="Option G")
    optionG_with_image=models.BooleanField(default=False)
    optionG_image=models.FileField(upload_to='question/%Y/%m/%d',blank=True)
    optionH=models.CharField(max_length=200,default="",blank=True,verbose_name="Option H")
    optionH_with_image=models.BooleanField(default=False)
    optionH_image=models.FileField(upload_to='question/%Y/%m/%d',blank=True)
    optionI=models.CharField(max_length=200,default="",blank=True,verbose_name="Option I")
    optionI_with_image=models.BooleanField(default=False)
    optionI_image=models.FileField(upload_to='question/%Y/%m/%d',blank=True)
    optionJ=models.CharField(max_length=200,default="",blank=True,verbose_name="Option J")
    optionJ_with_image=models.BooleanField(default=False)
    optionJ_image=models.FileField(upload_to='question/%Y/%m/%d',blank=True)
    
    
    class Meta:
        verbose_name='CBT QUESTION'
        verbose_name_plural='CBT QUESTIONS'

    def metafield(self):
        return self._meta.get_fields()

    def save(self, **kwargs):
        self.question_code="{}-{}-{}-{}".format(self.module,self.level,self.semester,self.pk)
        
        return super().save(**kwargs)

    def __str__(self):

        return self.question

class Cbt_sessions(models.Model):
    name=models.CharField(max_length=10,default="")

    class Meta:
        verbose_name='CBT SESSION'
        verbose_name_plural='CBT SESSIONS'
    def __str__(self):

        return self.name
class Cbt_students(models.Model):
   

    firstname=models.CharField(max_length=200,blank=True)
    
    lastname=models.CharField(max_length=200,blank=True)
    middlename=models.CharField(max_length=200,blank=True)
    username=models.CharField(max_length=200,blank=True)
    password=models.CharField(max_length=200)
    matricnumber=models.CharField(max_length=20,unique=True)
    email=models.EmailField(blank=True,unique=True)
    phonenumber=models.CharField(max_length=20,blank=True)
    level=models.ForeignKey(Cbt_level)
    session=models.ForeignKey(Cbt_sessions)
    semester=models.ForeignKey(Cbt_semester)
    faculty=models.ForeignKey(Cbt_faculty)
    department=models.ForeignKey(Cbt_department)
    picture=models.FileField(upload_to='passport/%Y/%m/%d',blank=True)
    
    class Meta:
        verbose_name='CBT STUDENT'
        verbose_name_plural='CBT STUDENTS'

    def __str__(self):

        return "{}".format(self.username)

    def save(self,**kwargs):
        print('^^^^^^^^^^^^^^^^^^^^^^^^^^ saving student')
        self.username=self.firstname+"_"+self.matricnumber
        return super().save(**kwargs)


class CBT_Exam(models.Model):
    #status choices
    STATUS_CHOICES=(
        ('SCHEDULED','SCHEDULED'),
        ('IN PROGRESS','IN PROGRESS'),
        ('ENDED','ENDED')
        )
    #exam date
    exam_date=models.DateTimeField()
    #module
    module=models.ForeignKey(Cbt_modules,unique=True)
    #duration
    time_length=models.IntegerField()
    #exam owner
    exam_owner=models.ForeignKey(User)
    #schedule stage
    status=models.CharField(max_length=200,choices=STATUS_CHOICES,default='SCHEDULED')
    instant_release=models.BooleanField(default=True)
    level=models.ForeignKey(Cbt_level,blank=True,null=True)
    exclussion=models.ManyToManyField(Cbt_students,blank=True,null=True)
    class Meta:
        verbose_name='CBT EXAM'
        verbose_name_plural='CBT EXAMS'

    def __str__(self):
        return "{} ".format(self.module)

    def clean(self):
        if len(Cbt_questions.objects.filter(module=self.module))<1:
            raise ValidationError('Please, the Questions for the '+ self.module.code + ' has not been Uploaded Yet !!!')
        super(CBT_Exam,self).clean()


    def save(self, *args, **kwargs):
        #self.exam_owner= User.objects.filter(is_staff=True)
        self.full_clean()
        super().save(*args,**kwargs)

class Cbt_ExamSession(models.Model):
    student=models.ForeignKey(Cbt_students,blank=True,null=True)
    question=models.ForeignKey(Cbt_questions)
    studentchoice=models.CharField(max_length=20)
    result=models.IntegerField()

    class Meta:
        verbose_name='CBT EXAMSESSION'
        verbose_name_plural='CBT EXAMSESSIONS'


class Cbt_StudentSession(models.Model):
    EXAMS_STATUS=(('NONE','NONE'),('STARTED','STARTED'),('FINISHED','FINISHED'),)
    student=models.ForeignKey(Cbt_students)
    module=models.ForeignKey(Cbt_modules)
    exam_status=models.CharField(max_length=20,choices=EXAMS_STATUS,default='NONE')

app/forms.py
"""
Definition of forms.
"""

from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _
from django.forms.utils import ValidationError
from app.models import Cbt_students
class BootstrapAuthenticationForm(AuthenticationForm):
    """Authentication form which uses boostrap CSS."""
    error_messages={'invalid_login':_('Re-Check You Matric Number !!!'),}

    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'User name'}))
    matricnumber = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'Matric Number'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder':'Password'}))
    def clean_matricnumber(self):
        print('clean_matricnumber.....................................',self.cleaned_data['matricnumber'])
        try:
            student=Cbt_students.objects.get(matricnumber= self.cleaned_data['matricnumber'])
            if student.username != self.cleaned_data['username']:
                 raise  ValidationError(self.error_messages['invalid_login'])
        except Exception as e:
            print(e)
            raise ValidationError(self.error_messages['invalid_login'])
        
        return self.cleaned_data['matricnumber']

app/templates/app/about.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<p>Use this area to provide additional information.</p>

{% endblock %}

app/templates/app/adminresults.html
{% extends "app/layout.html" %}
{% load exam_session %}
{% block content %}


<div class="row">
    <div class="col-sm-12">
        
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>No.</th>
                    <th>STUDENT</th>
                    <th>MODULE</th>
                    <th>DATE</th>
                    <th>TOTAL QUESTION</th>
                    <th>TOTAL SCORE</th>
                    

                </tr>
            </thead>
            <tbody>
                {% for result in results %}
                <tr>
                    <td>{{forloop.counter}}</td>
                
                    <td>{{result.student}}</td>
                    <td>{{result.module}}</td>
                    <td>{{result.date}}</td>
                    <td>{{result.total_questions}}</td>
                    <td>{{result.total_score}}</td>
                   

                </tr>
                {% endfor %}
            </tbody>
        </table>
        
    </div>
</div>



{% endblock %}

app/templates/app/boardpage.html
{% extends "app/layout.html" %}
{% block scripts %}
<script>
    // Cookies.remove('start_time', { path: '/questionpage' })
    // Cookies.remove('timeval', { path: '/questionpage' })
    // var loc=document.referrer
    
    // if(loc.indexOf('/questionpage')>0){
    //     window.location='/'
      //  console.log(loc.indexOf('/questionpage')+'***************************')

    // }
</script>
{% endblock %}
{% block content %}
{% load staticfiles %}

<div>
    <div class="row info-bar">
        <div class="col-md-3 ">
        <img class="pull-right" style="width:100px;height:80px;margin-top:2em" src="{% static 'app/images/fxlogic2.png' %}" />
            
          
        </div>
        <div class="col-md-6" >
       
        </div>
        <div class="col-md-3">
        <img class="pull-left img-thumbnail" style="width:100px;height:80px;margin-top:2em" src="/media/{{student.picture}}" />
            
          
        </div>
    </div>
    <div class="row info-candidate">
        <div class="col-md-2"></div>
        <div class="col-md-8 text-center info-panel">
            <div class="panel panel-info">
                <div class="panel-heading">Candidate information</div>
                <div class="panel-body">
                   <table class="table table-striped">
                       
                       <tr>
                           <td><b>First Name</b></td>
                           <td>{{student.firstname}}</td>

                       </tr>
                       <tr>
                           <td><b>Last Name</b></td>
                           <td>{{student.lastname}}</td>

                       </tr>
                       <tr>
                           <td><b>Matric Number</b></td>
                           <td>{{student.matricnumber}}</td>

                       </tr>
                       <tr>
                           <td><b>Department</b></td>
                           <td>{{student.department}}</td>

                       </tr>
                       <tr>
                           <td><b>Faculty</b></td>
                           <td>{{student.faculty}}</td>

                       </tr>
                       
                   </table>
                </div>


            </div>
        </div>
        <div class="col-md-2"></div>
        </div>
        <div class="row info-instruction" style="margin-left:6em" >
            <div style="font-weight:bolder;text-decoration:underline">INSTRUCTIONS:</div>
            <div class="col-md-8">
                <p>Student should read this information very well before starting the exam. If there is any issue with the instruction, make sure to notify any of our examiners for more detail.</p>
                <ul>
                    <li>
                        Make sure you have register for the Course Module you are about to be taking.
                    </li>
                    <li>
                        Make sure you have paid your school fee
                    </li>
                    <li>
                        The candidate information desplay above should be check if all the information are corect.
                    </li>
                    <li>
                        The picture thumbnail should be verify that you are the one appearing on the picture
                    </li>
                    <li>
                        GOOD LUCK !!! 
                    </li>
                </ul>
               
            </div>
        </div>
    <div class="row info-selector" style="margin-left:6em">
        <div class="col-md-12">
            <p>
                Select Your Exam Below:
            </p>
            <select id="modselect" class="form-control">
                {% for module in modules%}
                <option>
                    {{module}}
                </option>
                {% endfor %}
            </select>
        </div>
    </div>
    <div class="row info-start" style="margin-left:6em">
        <div class="col-md-12">
            
            <a id="startbtn" class="btn btn-default btn-primary" style="width:20%;margin-top:10px"  role="button">Start</a>
            
        </div>
    </div>
    <div class="row info-timer">
        <div class="col-md-10"></div>
        <div class="col-md-2 ">
            <div style="font-weight:bolder;color:green">Timer Info</div>
        </div>
    </div>
</div>
    {% endblock %}

app/templates/app/booklet.html
{% extends "app/layout.html" %}
{% load exam_session %}
{% load row_color %}
{% block content %}


<div class="row">
    <div class="col-sm-12">
        
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>No.</th>
                    <th>Question</th>
                    <th>Option A</th>
                    <th>Option B</th>
                    <th>Option C</th>
                    <th>Option D</th>
                    <th>Choice</th>
                    <th>Answer</th>

                </tr>
            </thead>
            <tbody>
                {% for question in questions%}
                {% get_exam_session question.question_code student %}
                {% colorize option.studentchoice question.answer%}
                <tr style="color: {{color}}">
                    <td>{{forloop.counter}}</td>
                
                    <td>{{question.question}}</td>
                    <td>{{question.optionA}}</td>
                    <td>{{question.optionB}}</td>
                    <td>{{question.optionC}}</td>
                    <td>{{question.optionD}}</td>
                    
                    <td>{{option.studentchoice}} </td>
                    <td>{{question.answer}} </td>

                </tr>
                {% endfor %}
            </tbody>
        </table>
        
    </div>
</div>



{% endblock %}

app/templates/app/contact.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

{% endblock %}

app/templates/app/exampage.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>

</body>
</html>

app/templates/app/login.html
{% extends "app/layout.html" %}
<script type="text/javascript">
    Cookies.remove('start_time', { path: '/questionpage' })
    Cookies.remove('timeval', { path: '/questionpage' })
</script>
{% block content %}
<div >
<h2>{{ title }}</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm" >
            <form action="." method="post" class="form-horizontal">
                {% csrf_token %}
                <h4>Use a CBT STUDENT Account to log in.</h4>
                <hr />
                <div class="form-group">
                    <label for="id_username" class="col-md-2 control-label">User name</label>
                    <div class="col-md-10">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_matricnumber" class="col-md-2 control-label">Matric Number</label>
                    <div class="col-md-10">
                        {{ form.matricnumber }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-md-2 control-label">Password</label>
                    <div class="col-md-10">
                        {{ form.password }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Log in" class="btn btn-default btn_login" />
                    </div>
                </div>
                {% if form.errors %}
                <p class="validation-summary-errors">Please enter a correct user name, matric number and password.</p>
                
                {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>
</div>
{% endblock %}


{% block scripts %}

    {% load staticfiles %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

app/templates/app/loginpartial.html
{% if user.is_authenticated %}
<form  id="logoutForm" action="/reset" method="post" class="navbar-right">
    {% csrf_token %}
    <ul  class="nav navbar-nav navbar-right">
        <li><span class="navbar-brand">Hello {{ user.username }}!</span></li>
        <li><a id="pauseme" href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
    </ul>

</form>

{% else %}

<ul style="margin: 20px 0 0 50px;font-weight: bold" class="nav navbar-nav navbar-right">
    <li><a href="{% url 'login' %}">Log in  </a> </li>
    <li><a href="{% url 'register' %}">Register  </a> </li>
</ul>

{% endif %}

app/templates/app/register.html
{% extends "app/layout.html" %}

{% block content %}
<div >
<h2>{{ title }}</h2>
    <div class="row">
    <div class="col-md-8">
        <section id="regForm" >
            <form action="/register" method="post" class="form-horizontal" enctype="multipart/form-data">
                {% csrf_token %}
                <h4>Use a CBT STUDENT Account to log in.</h4>
                <hr />
                <div class="panel panel-info">
                    <div class="panel-heading">Bio Data</div>
                    <div class="panel-body">


                        <div class="form-group">
                            <label for="id_firstname" class="col-md-2 control-label">First Name</label>
                            <div class="col-md-5">
                                {{ form.firstname }}
                            </div>
                        </div>
                       
                        <div class="form-group">
                            <label for="id_lastname" class="col-md-2 control-label">Last Name</label>
                            <div class="col-md-5">
                                {{ form.lastname }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="id_middlename" class="col-md-2 control-label">Middle Name</label>
                            <div class="col-md-10">
                                {{ form.middlename }}
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label for="id_email" class="col-md-2 control-label">Email</label>
                            <div class="col-md-10">
                                {{ form.email }}
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="id_password" class="col-md-2 control-label">Password</label>
                            <div class="col-md-10">
                                {{ form.password }}
                            </div>
                        </div>
                         <div class="form-group">
                            <label for="id_phonenumber" class="col-md-2 control-label">Phone Number</label>
                            <div class="col-md-10">
                                {{ form.phonenumber }}
                            </div>
                        </div>
                        
                    </div>
                </div>
                <div class="panel panel-info">
                    <div class="panel-heading">ImageUpload</div>
                    <div class="panel-body">
                        <div class="form-group">
                            <label for="id_upload" class="col-md-2 control-label">Picture Upload</label>
                            <div class="col-md-10">
                                {{ form.picture }}
                            </div>
                        </div>
                        </div>
                    </div>
                <div class="panel panel-info">
                    <div class="panel-heading">Accademics</div>
                    <div class="panel-body">
                        <div class="form-group">
                            <label for="id_matricnumber" class="col-md-2 control-label">Matric Number</label>
                            <div class="col-md-10">
                                {{ form.matricnumber }}
                            </div>
                        </div>

                       

                        <div class="form-group">
                            <label for="id_level" class="col-md-2 control-label">Level</label>
                            <div class="col-md-10">
                                {{ form.level }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="id_session" class="col-md-2 control-label">Session</label>
                            <div class="col-md-10">
                                {{ form.session }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="id_semester" class="col-md-2 control-label">Semester</label>
                            <div class="col-md-10">
                                {{ form.semester }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="id_faculty" class="col-md-2 control-label">Faculty</label>
                            <div class="col-md-10">
                                {{ form.faculty }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="id_department" class="col-md-2 control-label">Department</label>
                            <div class="col-md-10">
                                {{ form.department }}
                            </div>
                        </div>
                        
                        </div>
                    </div>
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="hidden" name="next" value="/" />
                                <input type="submit" value="Submit" style="width:100%" class="btn btn-info" />
                            </div>
                        </div>
                        {% if form.errors %}
                        <p class="validation-summary-errors">Please enter a correct user name and password.</p>
                        <p>{{form.errors}}</p>
                        {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm">
            
        </section>
    </div>
</div>
</div>
{% endblock %}


{% block scripts %}

    {% load staticfiles %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}